name: Monthly Notion Summary

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  notion-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "openai>=1.0.0" requests feedparser

      - name: Push Summary to Notion
        run: python push_summary.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_BASE_URL: https://api.deepseek.com
          QUERY_KEYWORDS: ${{ secrets.QUERY_KEYWORDS }}
