name: Monthly Notion Summary

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号 UTC 零点执行
  workflow_dispatch:

jobs:
  notion-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests openai feedparser

      - name: Push Summary to Notion
        run: python push_summary.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QUERY_KEYWORDS: ${{ secrets.QUERY_KEYWORDS }}
